# Generated by Django 4.1.5 on 2023-04-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='asd',
        ),
    ]
