# Generated by Django 4.1.5 on 2023-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_comment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='../media/cards/vivo.jfif', max_length=200, upload_to='cards', verbose_name='Resim'),
        ),
    ]
