# Generated by Django 4.1.5 on 2023-05-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0005_alter_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='author',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı - Satıtcı'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/vivo.jfif', max_length=200, upload_to='cards', verbose_name='Resim'),
        ),
    ]
