# Generated by Django 4.1.5 on 2023-05-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_remove_card_author_card_user_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Göster'),
        ),
    ]
