# Generated by Django 4.1.5 on 2023-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_card_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
    ]
